workflows:
  macos-release:
    name: macOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Build macOS App
        script: flutter build macos
      - name: Copy .app to output folder
        script: |
          mkdir -p ~/build_output
          APP_FOLDER="build/macos/Build/Products/Release/conversion_number.app"

          if [ -d "$APP_FOLDER" ]; then
            cp -R "$APP_FOLDER" ~/build_output/
          else
            echo "❌ ERROR: .app file not found!"
            exit 1
          fi
    artifacts:
      - ~/build_output/conversion_number.app

